config/routes.rb
Rails.application.routes.draw do
  get '/start/resources', to: 'pages#start_resources'
  get '/activities/resources', to: 'pages#activities_resources'
  get '/journeys/resources', to: 'pages#journeys_resources'
  get '/routes/resources', to: 'pages#routes_resources'

  get '/start/activities', to: 'pages#start_activities'
  get '/activities/activities', to: 'pages#activities_activities'
  get '/journeys/activities', to: 'pages#journeys_activities'
  get '/routes/activities', to: 'pages#routes_activities'

  root to: 'pages#start_resources'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_theme


  def start_resources
  end


  def start_activities
  end


  def journeys_resources
  end


  def journeys_activities
  end


  def activities_activities
  end


  def activities_resources
  end


  def routes_activities
  end


  def routes_resources
  end


  private


  def set_theme
    @mode, @theme =
      if request.original_url.split('/').last == 'activities'
        ['activity', 'theme-blue']
      else
        ['resource', 'theme-red']
      end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeWise</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="site-section">
    <div class="container">

      <div class="row justify-content-center mb-5">
        <div class="col-md-12 col-lg-12 col-sm-12 text-center border-primary <%= @theme %>-border-primary">
          <h2 class="font-weight-light text-primary">
            <a href="<%= @theme == 'theme-blue' ? start_activities_path : start_resources_path  %>" class="<%= @theme %>">
              TimeWise
            </a>
          </h2>
          <p class="color-black-opacity-5">Helping you make the most of your travel time</p>
        </div>
      </div>

      <%= yield %>
    </div>
    <div class="text-center small mt-5">Icons made by <a href="https://www.flaticon.com/authors/roundicons" class="<%= @theme %>" title="Roundicons">Roundicons</a> from <a href="https://www.flaticon.com/" class="<%= @theme %>" title="Flaticon">www.flaticon.com</a></div>
  </div>


  </body>
</html>

app/views/pages/_activities.html.erb
    <div class="row mb-3">

      <div class="col-md-12 col-lg-12 mb-4 mb-lg-4 mx-auto">
        <div class="h-entry">
          <!--          <img src="images/img_2.jpg" alt="Free Website Template by Free-Template.co" class="img-fluid">-->

          <h3 class="h5 text-black mb-3">
            What activities would you like to do on your trip?
          </h3>

          <form action="#" method="post">

            <fieldset>
            <!-- <legend>Single Element Checkboxes</legend>-->

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Make phone calls or send messages',
                             checked: true
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Read',
                             checked: false
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Write or edit documents',
                             checked: true
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Browse the Internet (including social media, travel info, etc.)',
                             checked: true
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Watch videos',
                             checked: false
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Listen to music, podcasts, audiobooks or radio',
                             checked: false
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Play games',
                             checked: false
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Take a nap',
                             checked: true
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Talk to other passengers',
                             checked: false
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Care for other passengers',
                             checked: false
                         }
              %>

              <%= render partial: 'activity_list_item',
                         locals: {
                             title: 'Eat or drink',
                             checked: true
                         }
              %>
            </fieldset>


            <%= render partial: 'navigation_buttons',
                       locals:  {
                           forward_url: flow_url,
                           back_url:    @mode == 'activity' ? start_activities_url : start_resources_url,
                       }
            %>


          </form>

      </div>

    </div>

  </div>

app/views/pages/_activity_item.html.erb
<%
  sym_name, sym_color =
      case symbol
      when :check
        ['check', 'green']
      when :cross
        ['times', 'red']
      when :question
        ['question', 'yellow']
      else
        ''
      end
%>

<div class="row resource-activity">
  <div class="col-1 px-0 mx-lg-0 mx-md-0">
    <div class="row">
      <div class="col">
        <a data-toggle="collapse"
           class="<%= @theme %>"
           href="#<%= id %>"
           role="button"
           aria-expanded="false"
           aria-controls="<%= id %>">
                <i class="fas fa-plus"></i>
        </a>
      </div>
      <div class="col">
        <i class="fas fa-<%= sym_name %> <%= sym_color %>"></i>
      </div>
    </div>

  </div>


  <div class="col-8 pr-0">
    <a data-toggle="collapse"
       class="<%= @theme %>"
       href="#<%= id %>"
       role="button"
       aria-expanded="false"
       aria-controls="<%= id %>">
      <%= title %>
    </a>
  </div>
</div>

app/views/pages/_activity_list_item.html.erb
<div class="s-cb s-cb-<%= @theme %> row border-top py-3">
  <div class="col-2 my-auto">
    <input type="checkbox" id="s_input_1" class="m-0" <%= 'checked' if checked %>>
  </div>
  <div class="col-10 my-auto">
    <label for="s_input_1" class="mb-0">
      <%= title %>
    </label>
  </div>
</div>

app/views/pages/_navigation_buttons.html.erb
<br>

<div class="row">

  <% if back_url %>
  <div class="col">
    <a href="<%= back_url %>" class="col-12 btn btn-primary btn-md text-white <%= @theme %>-bg">
      <i class="fas fa-chevron-left"></i>&nbsp;&nbsp;Back
    </a>
  </div>
  <% end %>

  <% if forward_url %>
  <div class="col">
    <a href="<%= forward_url %>" class="col-12 btn btn-primary btn-md text-white <%= @theme %>-bg">
      Next &nbsp;<i class="fas fa-chevron-right"></i>
    </a>
  </div>
  <% end %>

</div>

app/views/pages/_resource_item_with_route.html.erb
<% av_class = availability.split(' ').join('-').downcase %>

<div class="col-lg-3 col-md-3 col-sm">
  <div class="p-4 resource-item <%= av_class %>">
    <div class="row">
      <div class="col-12">
        <div class="row">
          <div class="col-10 px-0">
            <div class="resource-title">
              <%= title %>
            </div>
            <div class="resource-description"><%= availability %></div>
          </div>
          <div class="col-2 px-0 text-center">
            <%= image_tag "#{av_class}.png", class: 'emoticon' %>


            <a data-toggle="collapse" href="#<%= id %>" role="button"
               aria-expanded="false"
               aria-controls="<%= id %>"
               class="accordion-item mb-0 <%= @theme %>">
              <i class="fas fa-chevron-circle-down"></i>
            </a>


          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="collapse" id="<%= id %>">
    <%= render partial: 'pages/route_resources',
               locals:  {
                   route_stations: route_stations
               }
    %>
  </div>

</div>

app/views/pages/_start.html.erb
<div class="row mb-3">

  <div class="col-md-6 col-lg-10 mb-4 mb-lg-4 mx-auto">

        <h3 class="h5 text-black mb-3">Enter details of your trip</h3>

    <div class="row">
      <div class="col">


        <form action="#" method="post">
          <div class="form-group d-flex">
            <input type="text" class="form-control" placeholder="From..." value="Nottingham">
          </div>

          <div class="form-group">
            <input type="text" class="form-control" placeholder="To..." value="London">
          </div>

          <div class="form-group row">
            <div class="col-4">
              <input type="text" class="form-control datepicker" placeholder="Departure" value="15/01/2020"/>
            </div>

            <div class="col-4 px-0">
              <select id="" class="form-control" name="">
                <option value="1">Leaving at</option>
                <option value="1">Arriving by</option>
              </select>
            </div>

            <div class="col-4">
              <input type="text" class="form-control" placeholder="HH:MM" value="08:00">
<!--              <select class="form-control" name="hours">-->
<!--                <option value="1">00</option>-->
<!--                <option value="1">01</option>-->
<!--                <option value="1">02</option>-->
<!--                <option value="1">03</option>-->
<!--                <option value="1">04</option>-->
<!--                <option value="1">05</option>-->
<!--                <option value="1">06</option>-->
<!--                <option value="1">07</option>-->
<!--                <option value="1" selected="selected">08</option>-->
<!--                <option value="1">09</option>-->
<!--                <option value="1">10</option>-->
<!--                <option value="1">11</option>-->
<!--                <option value="1">12</option>-->
<!--                <option value="1">13</option>-->
<!--                <option value="1">14</option>-->
<!--                <option value="1">15</option>-->
<!--                <option value="1">16</option>-->
<!--                <option value="1">17</option>-->
<!--                <option value="1">18</option>-->
<!--                <option value="1">19</option>-->
<!--                <option value="1">20</option>-->
<!--                <option value="1">21</option>-->
<!--                <option value="1">22</option>-->
<!--                <option value="1">23</option>-->
<!--              </select>-->
            </div>

          </div>

          <div class="form-group cntr">
            <label for="opt1" class="radio">
              <input type="radio" name="rdo" id="opt1" class="hidden" checked/>
              <span class="label <%= @theme %>-label"></span>One way
            </label>

            <label for="opt2" class="radio">
              <input type="radio" name="rdo" id="opt2" class="hidden <%= @theme %>"/>
              <span class="label <%= @theme %>-label"></span>Return
            </label>
          </div>

          <%= render partial: 'navigation_buttons',
                     locals:  {
                         forward_url: flow_url,
                         back_url:    false,
                     }
          %>

        </form>

  </div>
</div>

  </div>
</div>

app/views/pages/activities_activities.html.erb
<%= render partial: 'pages/activities',
           locals:  {
               flow_url: journeys_activities_path
           }
%>

app/views/pages/activities_resources.html.erb
<%= render partial: 'pages/activities',
           locals:  {
               flow_url: journeys_resources_path
           }
%>

app/views/pages/journeys_activities.html.erb
    <div class="row mb-3">

      <div class="col-md-10 col-lg-10 mb-4 mb-lg-4 mx-auto">

          <div class="h-entry">
            <h3 class="h5 text-black mb-3">Select your journey</h3>
          </div>


        <div class="row">
          <div class="col-12">
            <div class="row mx-2">
              <div class="col-12 mx-auto text-center mb-2 pb-2 journey-title">
                OUT: Saturday Feb 1 2020
              </div>

              <form action="#" method="post" class="row">
                <div class="col-12 text-center my-3 pager">
                  <i class="fas fa-angle-up"></i>&nbsp;&nbsp;Earlier trains
                </div>

                <!-- form-row 1 -->
                <div class="col-12 border p-3 rounded mb-2 <%= @theme %>-journey-item">

                  <div class="row">
                    <div class="col-2">
                      <label for="opt1" class="radio">
                        <input type="radio" name="rdo" id="opt1" class="hidden"/>
                        <span class="label <%= @theme %>-label"></span>
                      </label>
                    </div>
                    <div class="col-3">
                      <div class="time">08:05</div>
                      <div class="station">Nottingham</div>
                    </div>
                    <div class="col-2 text-center">
                      <i class="fas fa-long-arrow-alt-right dark-grey"></i>
                    </div>
                    <div class="col-5">
                      <div class="time">09:55</div>
                      <div class="station">London St Pancras International</div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                      <div class="text-center mt-3">
                        <a data-toggle="collapse"
                           href="#collapse-1"
                           role="button"
                           aria-expanded="false"
                           aria-controls="collapse-1"
                           class="accordion-item mb-0 <%= @theme %> more-link">
                          Travel Activities
                          &nbsp;
                          <i class="fas fa-chevron-circle-down"></i>
                        </a>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                       <div class="collapse" id="collapse-1">
                        <div class="pt-2 ml-4">

                          <%= render partial: 'pages/journey_item_activities',
                                     locals: {
                                         id_1: 'activity-1',
                                         id_2: 'activity-2',
                                         id_3: 'activity-3',
                                         id_4: 'activity-4',
                                         id_5: 'activity-5',
                                     }
                          %>

                        </div>
                      </div>
                    </div>
                  </div>

                </div>


                <!-- form-row 2-->


                <div class="col-12 border p-3 rounded mb-2 <%= @theme %>-journey-item">

                  <div class="row">
                    <div class="col-2">
                      <label for="opt2" class="radio">
                        <input type="radio" name="rdo" id="opt2" class="hidden" checked/>
                        <span class="label <%= @theme %>-label"></span>
                      </label>
                    </div>
                    <div class="col-3">
                      <div class="time">08:09</div>
                      <div class="station">Nottingham</div>
                    </div>
                    <div class="col-2 text-center">
                      <i class="fas fa-long-arrow-alt-right dark-grey"></i>
                    </div>
                    <div class="col-5">
                      <div class="time">10:04</div>
                      <div class="station">London St Pancras International</div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                      <div class="text-center mt-3">
                        <a data-toggle="collapse" href="#collapse-2"
                           role="button"
                           aria-expanded="false"
                           aria-controls="collapse-2"
                           class="accordion-item mb-0 <%= @theme %> more-link">
                          Travel Activities
                          &nbsp;
                          <i class="fas fa-chevron-circle-down"></i>
                        </a>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                      <div class="collapse" id="collapse-2">
                        <div class="pt-2 ml-4">

                          <%= render partial: 'pages/journey_item_activities',
                                     locals: {
                                         id_1: 'activity-6',
                                         id_2: 'activity-7',
                                         id_3: 'activity-8',
                                         id_4: 'activity-9',
                                         id_5: 'activity-10',
                                     }
                          %>



                        </div>
                      </div>
                    </div>
                  </div>


                  <!--                  </a>-->

                </div>


                <!-- form-row 3-->


                <div class="col-12 border p-3 rounded mb-2 <%= @theme %>-journey-item">


                  <div class="row">
                    <div class="col-2">
                      <label for="opt3" class="radio">
                        <input type="radio" name="rdo" id="opt3" class="hidden"/>
                        <span class="label <%= @theme %>-label"></span>
                      </label>
                    </div>
                    <div class="col-3">
                      <div class="time">08:34</div>
                      <div class="station">Nottingham</div>
                    </div>
                    <div class="col-2 text-center">
                      <i class="fas fa-long-arrow-alt-right dark-grey"></i>
                    </div>
                    <div class="col-5">
                      <div class="time">10:15</div>
                      <div class="station">London St Pancras International</div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                      <div class="text-center mt-3">
                        <a data-toggle="collapse"
                           href="#collapse-3"
                           role="button"
                           aria-expanded="false"
                           aria-controls="collapse-3"
                           class="accordion-item mb-0 <%= @theme %> more-link">
                            Travel Activities
                          &nbsp;
                          <i class="fas fa-chevron-circle-down"></i>
                        </a>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                      <div class="collapse" id="collapse-3">
                          <div class="pt-2 ml-4">

                            <%= render partial: 'pages/journey_item_activities',
                                       locals: {
                                           id_1: 'activity-11',
                                           id_2: 'activity-12',
                                           id_3: 'activity-13',
                                           id_4: 'activity-14',
                                           id_5: 'activity-15',
                                       }
                            %>



                        </div>
                      </div>
                    </div>
                  </div>


                </div>


                <!-- form-row 4-->
                <div class="col-12 border p-3 rounded mb-2 <%= @theme %>-journey-item">
                  <div class="row">
                    <div class="col-2">
                      <label for="opt4" class="radio">
                        <input type="radio" name="rdo" id="opt4" class="hidden"/>
                        <span class="label <%= @theme %>-label"></span>
                      </label>
                    </div>
                    <div class="col-3">
                      <div class="time">09:05</div>
                      <div class="station">Nottingham</div>
                    </div>
                    <div class="col-2 text-center">
                      <i class="fas fa-long-arrow-alt-right dark-grey"></i>
                    </div>
                    <div class="col-5">
                      <div class="time">10:52</div>
                      <div class="station">London St Pancras International</div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                      <div class="text-center mt-3">
                        <a data-toggle="collapse"
                           href="#collapse-4"
                           role="button"
                           aria-expanded="false"
                           aria-controls="collapse-4"
                           class="accordion-item mb-0 <%= @theme %> more-link">
                          Travel Activities
                          &nbsp;
                          <i class="fas fa-chevron-circle-down"></i>
                        </a>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                      <div class="collapse" id="collapse-4">
                        <div class="pt-2 ml-4">

                          <%= render partial: 'pages/journey_item_activities',
                                     locals: {
                                         id_1: 'activity-16',
                                         id_2: 'activity-17',
                                         id_3: 'activity-18',
                                         id_4: 'activity-19',
                                         id_5: 'activity-20',
                                     }
                          %>


                        </div>
                      </div>
                    </div>
                  </div>

                </div>

                <div class="col-12 text-center my-3 pager">
                  <i class="fas fa-angle-down"></i>&nbsp;&nbsp;Later trains
                </div>

                <div class="col-12">
                  <%= render partial: 'navigation_buttons',
                             locals:  {
                                 forward_url: routes_activities_url,
                                 back_url:    activities_activities_url,
                             }
                  %>
                </div>
              </form>

            </div>
          </div>


          <% if false %>
            <div class="col-6">
              <div class="row mx-2">
                <div class="col-12 mx-auto text-center mb-2 pb-2">
                </div>
              </div>
            </div>
          <% end %>


        </div>

      </div>

    </div>

app/views/pages/start_activities.html.erb
<%= render partial: 'pages/start',
           locals: {
               title: 'Activities',
               flow_url: activities_activities_path
           }
%>

app/views/pages/start_resources.html.erb
<%= render partial: 'pages/start',
           locals: {
               title: 'Resources',
               flow_url: activities_resources_path
           }
%>